<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>bf584e6f-da93-47c7-b7ca-c57d773fad61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d959fcdb-bb62-4677-b45c-0e315f822191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a13ccd2-2795-4ef0-b20b-c58dbf2b48be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maximum-scale</name>
      <type>Main</type>
      <value>1.6</value>
      <webElementGuid>4acad113-d79d-4f0c-b9df-5b1b8144606d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-scalable</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>0694a7c2-1f8c-42f9-acfc-f425d48e5a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>98457941-d961-44d0-9f79-7f7d16685175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Ponsel / Email</value>
      <webElementGuid>45246dc1-bda8-4454-93ca-ff46198a5188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-custom w-11/12</value>
      <webElementGuid>7a498958-f6bd-432c-934e-278f6a434098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-blue-1 flex flex-col min-h-screen text-white font-montserrat&quot;]/div[@class=&quot;vm--container&quot;]/div[@class=&quot;vm--modal modal-classes full-height mx-auto&quot;]/div[@class=&quot;text-white layout-login-wrapper&quot;]/form[@class=&quot;mb-6&quot;]/div[@class=&quot;border border-opacity-50 rounded-full px-7 py-3 mb-4&quot;]/div[@class=&quot;relative h-5 flex items-center&quot;]/input[@class=&quot;input-custom w-11/12&quot;]</value>
      <webElementGuid>287cfa92-4df4-4133-b0d6-42613cf7f109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>f7e06375-2fb4-41a8-9de4-3114edb0753b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div[2]/div/form/div/div/input</value>
      <webElementGuid>c0a33a84-38d2-49c5-9d22-b0a235ef8b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>1ae5c9ce-2ec3-4e78-8542-a1baf00e5bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username' and @placeholder = 'Nomor Ponsel / Email']</value>
      <webElementGuid>a3bdc526-292a-4e45-bf04-650844606f2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
