<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Grace D. Sitangganggrace.sitanggang03gmail.com</name>
   <tag></tag>
   <elementGuidId>72cff035-fa37-4750-b498-a78f9920b552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div/div/ul/li/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tgnCOd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10eec2ef-7aba-49a8-9e32-2ddcdd6414d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tgnCOd</value>
      <webElementGuid>22b5d4d2-96a2-4e86-8c92-da86fed99b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grace D. Sitangganggrace.sitanggang03@gmail.com</value>
      <webElementGuid>49953a0c-e41e-4405-a94b-07a3ddf94f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_container&quot;)/div[@class=&quot;zWl5kd&quot;]/div[@class=&quot;DRS7Fe bxPAYd k6Zj8d&quot;]/div[@class=&quot;pwWryf bxPAYd&quot;]/div[@class=&quot;Wxwduf Us7fWe JhUD8d&quot;]/div[@class=&quot;WEQkZc&quot;]/div[@class=&quot;bCAAsb&quot;]/form[1]/span[1]/section[@class=&quot;aTzEhb&quot;]/div[@class=&quot;CxRgyd&quot;]/div[1]/div[@class=&quot;zeRELc&quot;]/div[@class=&quot;pQ0lne&quot;]/ul[@class=&quot;OVnw0d&quot;]/li[@class=&quot;JDAKTe ibdqA W7Aapd zpCp3 SmR8&quot;]/div[@class=&quot;lCoei YZVTmd SmR8&quot;]/div[@class=&quot;d2laFc&quot;]/div[@class=&quot;tgnCOd&quot;]</value>
      <webElementGuid>cbffaf0a-550e-4fc2-aacb-bbb8006ead92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div/div/ul/li/div/div/div</value>
      <webElementGuid>7fc5414d-05f7-4008-9311-3de830fed2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bioskoponline.com'])[1]/following::div[11]</value>
      <webElementGuid>dacbfda6-e016-4f91-b382-62f1591554a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div</value>
      <webElementGuid>98ed7278-df78-4505-b8ef-791c45b969f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Grace D. Sitangganggrace.sitanggang03@gmail.com' or . = 'Grace D. Sitangganggrace.sitanggang03@gmail.com')]</value>
      <webElementGuid>481358aa-c288-46d0-a009-d4a58ec72707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
