<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Not now</name>
   <tag></tag>
   <elementGuidId>a5308795-21be-4022-afff-9c37b29dced5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[2]/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._2iem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>531ab7ac-e7a0-4b8f-a899-02e3e9a16ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2iem</value>
      <webElementGuid>75153176-7384-4a49-90a8-dc47e96a4e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not now</value>
      <webElementGuid>20101aba-dfa6-4450-be3c-113a4fa6a1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;_4-u5 _30ny&quot;]/div[@class=&quot;_4-u2 _1w1t _4-u8 _52jv&quot;]/div[2]/div[2]/a[@class=&quot;_97w6&quot;]/span[@class=&quot;_2iem&quot;]</value>
      <webElementGuid>7e4ed02e-6b68-4115-a3de-ed7a293068fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div[2]/div[2]/a/span</value>
      <webElementGuid>88e80752-45a3-405e-8465-00a18f2bd440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Accessing App'])[1]/following::span[1]</value>
      <webElementGuid>322211aa-360a-49eb-b1e8-c1ff64778b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to Facebook'])[1]/following::span[1]</value>
      <webElementGuid>6b295e57-b2f1-469d-a599-54d2128feca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::span[1]</value>
      <webElementGuid>89892653-35f1-4816-b2be-6c79fe19fe0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/preceding::span[1]</value>
      <webElementGuid>50f831cb-3873-4f3e-816b-b3ba1d7f5f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Not now']/parent::*</value>
      <webElementGuid>86a8cccc-354b-4a5c-bc36-8bc7409ae44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
      <webElementGuid>b147cc79-ef9a-49ba-8da1-dcbbde401b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Not now' or . = 'Not now')]</value>
      <webElementGuid>c10a56d1-a6c1-46c3-9e02-1e223ab3fed5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
